### ISSUE TITLE
Error with cache.load

### ISSUE THREAD

**Issue by rsm5139** [jwkvam/bowtie#121]
I'm getting an error when I use `bowtie.cache.load`. As far as I can tell, the correct value is loading and everything functions normally. I'm not sure where this error comes from. I'm also using `Schedule`, but I managed to get that to work fine when not loading from the cache. 

As I make more changes, I may be able to give more details about this.

```
  File "/Users/rsm5139/anaconda3/envs/learning-bowtie/lib/python3.6/site-packages/eventlet/greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "./build/src/server.py", line 59, in foo
    func()
  File "/Users/rsm5139/Git/learning-bowtie/step_1.py", line 23, in timed_event
    ticker = cache.load('scheduled')
  File "/Users/rsm5139/anaconda3/envs/learning-bowtie/lib/python3.6/site-packages/bowtie/cache.py", line 58, in load
    return msgpack.unpackb(bytes(event.get(timeout=10)), encoding='utf8')
  File "/Users/rsm5139/anaconda3/envs/learning-bowtie/lib/python3.6/site-packages/eventlet/queue.py", line 313, in get
    return waiter.wait()
  File "/Users/rsm5139/anaconda3/envs/learning-bowtie/lib/python3.6/site-packages/eventlet/queue.py", line 141, in wait
    return get_hub().switch()
  File "/Users/rsm5139/anaconda3/envs/learning-bowtie/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 295, in switch
    return self.greenlet.switch()
queue.Empty
^Cwsgi exiting
```

**Comment by jwkvam** [comment]
Thanks again for your report. I believe you are running into a tricky technical issue that is not documented IIRC :(

Whenever bowtie is running a scheduled task, it isn't communicating with any client directly. That's because the task was initiated by the server, in other cases, it's initiated by the client through an event like clicking on a button. Therefore when you send a "load" message in a scheduled task it's broadcast to everyone and in this case I don't believe callbacks are supported, which is how the data get's back into the python code.

More info is here:
https://flask-socketio.readthedocs.io/en/latest/#broadcasting

I believe the correct solution to this is to broadcast a message to all the clients and then have the clients initiate a message with the server. Then we can successfully load the data from the client since bowtie will be communicating directly with clients individually.

I can investigate more later. I don't think there's an easy work around. I would like this feature but it may take a while for me to get around to. If you are interested in hacking on this feel free, you'll have to dig into the guts of bowtie though :)

**Comment by rsm5139** [comment]
I see. That changes some things for me. I was storing the timer value in the cache. However, since this cache is shared that means it won't work for multiple users. I need every new user to start with a set time limit.
Is there any way to store a value for a user, like a session cookie?

**Comment by jwkvam** [comment]
I like how you are stress testing many of bowtie's features :)

To be clear, the cache itself is not shared. The values will be the same because the scheduled function gets run for all users. At least that's what I **think**. Backtracking a little, actually I think this should work if you only have one client.

Unfortunately, I think what you are trying to do isn't possible right now. Bowtie needs the feature I was describing above, so it can address clients individually even when initiated by a scheduled task.

Sadly, sessions and cookies are not viable in my experience. Before I built the cache mechanism I was considering that and asked the flask socketio maintainer about it.

https://github.com/miguelgrinberg/Flask-SocketIO/issues/422

**Comment by jwkvam** [comment]
@rsm5139 I think I've got something that'll work for you. I wrote a pager object which will tell the server to make the client send a message back to the server. I tested an example use of this below. I hope you can adapt it to your needs. Let me know how it goes.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Example Bowtie App.
"""

from bowtie.control import Nouislider
from bowtie.visual import Plotly
from bowtie import command
from bowtie import Pager
from bowtie import cache

import numpy as np
from numpy import random as rng
import plotlywrapper as pw


pager = Pager()
sigma = Nouislider(caption='Sigma', start=0., minimum=0.1, maximum=50.)
mainplot = Plotly()


def initialize():
    cache.save('data', [0.] * 100)


def upgraph():
    data = cache.load('data')
    value = float(sigma.get())
    data.pop(0)
    data.append(value * rng.randn() + data[-1])
    mainplot.do_all(pw.line(data).to_json())
    cache.save('data', data)


def walk():
    pager.notify()


@command
def construct():
    from bowtie import Layout
    layout = Layout(debug=False)
    layout.add_sidebar(sigma)
    layout.add(mainplot)
    layout.load(initialize)
    layout.schedule(0.1, walk)
    layout.respond(pager, upgraph)

    layout.build()
```

**Comment by rsm5139** [comment]
Thank you, I'll try that out.

**Comment by rsm5139** [comment]
I still get the same errors, though it's possible that the app is running a little better. 
Furthermore, I tested this live and my timer function won't work. The countdown timer ends up being shared by all users. If 2 browser windows are open and one timer is at "0", for example, then anyone else who navigates to the URL will start at 0. (Well, technically the timer is initialized at 30, then jumps right to 0.)
Here is the URL for reference, though the URL will likely change in the future. https://lake-jdm.herokuapp.com

**Comment by rsm5139** [comment]
Ah, my apologies. I am working on 2 different apps, and I mistakenly ran the wrong one before. It turns out the update you made DID work! I can have 2 instances running and the timer is unique to each user. Thank you again for the help!

**Comment by jwkvam** [comment]
Awesome! Looks pretty cool. By the way, you'll want to recompile your app with production settings to reduce the size of the bundle.js file. It'll reduce it from about 30 MB to 1 MB.

![image](https://cloud.githubusercontent.com/assets/86304/25498073/8076af82-2b3b-11e7-974c-68378bd56539.png)
